export default {
    channels: [
        {
            _id: 'techgiants',
            name: 'Tech giants main',
            image: './images/techmain.jpg',
            description:'the biggest tech community',
            members:'12000',
            admins: '12',
            age: '3 years',
        },
        {
            _id: 'tgmovies',
            name: 'TG Movies',
            image: './images/movies.jpg',
            description:'Get the latest movies when they release',
            members:'5000',
            admins: '6',
            age: '2 years',
        },
        {
            _id: 'Starlabs',
            name: 'Starlabs ',
            image: './images/starlabs.jpg',
            description:'Get all mod apks , games and cracked softwares',
            members:'10,000',
            admins: '8',
            age: '2 years',
        },
        {
            _id: 'Breakthrough',
            name: 'Breakthrough',
            image: './images/breakthrough.jpg',
            description:'Best place to be during this times',
            members:'4000',
            admins: '5',
            age: '2 years',
        },
        {
            _id: 'Mensconfrence',
            name: 'Mens confrence ',
            image: './images/mensconfrence.jpg',
            description:'we turn boys to men',
            members:'2000',
            admins: '6',
            age: '2 years',
        },
        {
            _id: 'TGMusic',
            name: ' TG Music',
            image: './images/music.jpg',
            description:'We made you a better playlist  ',
            members:'2000',
            admins: '4',
            age: '2 years',
        },
    ],
}